import test from 'node:test';import assert from 'node:assert/strict';
import {accounts,digest} from '../worker/accounts.mjs';
import {setup} from './helpers/accounts-env.mjs';

const origin='https://auth.example.com';
const req=(path,method='GET',data,headers={})=>new Request(origin+'/account/'+path,{method,headers:{...(method!=='GET'?{Origin:origin}:{}),...headers},...(data===undefined?{}:{body:typeof data==='string'||data instanceof Uint8Array?data:JSON.stringify(data)})});
const jar=r=>r.headers.get('Set-Cookie')?.split(';')[0];
function sender(){const sent=[];return {sent,fetch:async(_url,options)=>{sent.push(JSON.parse(options.body));return Response.json({id:'sent'})}};}
async function invitedLogin(env,db,address='alice@example.com'){db.prepare('INSERT OR IGNORE INTO creator_invitations(email) VALUES(?)').run(address);const mail=sender();const started=await accounts(req('api/email/start','POST',{email:address}),env,mail.fetch);assert.equal(started.status,200);const token=mail.sent[0].text.match(/#token=([a-f0-9]+)/)[1];const finished=await accounts(req('api/email/finish','POST',{token},{Cookie:jar(started)}),env);assert.equal(finished.status,200);const cookie=jar(finished),me=await(await accounts(req('api/me','GET',undefined,{Cookie:cookie}),env)).json();return{cookie,me,token,flow:jar(started)};}
test('account feature is off by default and cross-origin mutations rejected',async()=>{const {env}=setup();assert.equal((await accounts(req('api/config'),{})).status,200);assert.equal((await accounts(req('api/me'),{})).status,503);assert.equal((await accounts(req('api/email/start','POST',{email:'x@example.com'},{Origin:'https://evil.example'}),env)).status,403);});
test('email tokens are hashed, browser-bound, single-use, and sessions revoke on logout',async()=>{const {env,db}=setup();const {cookie,me,token,flow}=await invitedLogin(env,db);assert(!db.prepare('SELECT * FROM creator_sessions').all().some(x=>JSON.stringify(x).includes(cookie.split('=')[1])));assert.equal((await accounts(req('api/email/finish','POST',{token},{Cookie:flow}),env)).status,400);assert.equal((await accounts(req('api/logout','POST',undefined,{Cookie:cookie}),env)).status,403);assert.equal((await accounts(req('api/logout','POST',undefined,{Cookie:cookie,'X-CSRF-Token':me.csrf}),env)).status,200);assert.equal((await accounts(req('api/me','GET',undefined,{Cookie:cookie}),env)).status,401);});
test('email GET does not consume token; another browser cannot redeem; token expires',async()=>{const {env,db}=setup();db.prepare('INSERT INTO creator_invitations(email) VALUES(?)').run('alice@example.com');const mail=sender();const start=await accounts(req('api/email/start','POST',{email:'alice@example.com'}),env,mail.fetch);const token=mail.sent[0].text.match(/#token=([a-f0-9]+)/)[1];await accounts(req('verify'),env);assert.equal(db.prepare('SELECT COUNT(*) n FROM creator_challenges').get().n,1);assert.equal((await accounts(req('api/email/finish','POST',{token}),env)).status,400);db.prepare('UPDATE creator_challenges SET expires_at=0').run();assert.equal((await accounts(req('api/email/finish','POST',{token},{Cookie:jar(start)}),env)).status,400);});
test('unknown emails get generic response, no mail; daily limits protect delivery',async()=>{const {env,db}=setup();const mail=sender();const r=await accounts(req('api/email/start','POST',{email:'unknown@example.com'}),env,mail.fetch);assert.equal(r.status,200);assert.equal(mail.sent.length,0);db.prepare('INSERT INTO creator_invitations(email) VALUES(?)').run('alice@example.com');for(let i=0;i<5;i++)assert.equal((await accounts(req('api/email/start','POST',{email:'alice@example.com'}),env,mail.fetch)).status,200);assert.equal((await accounts(req('api/email/start','POST',{email:'alice@example.com'}),env,mail.fetch)).status,429);assert.equal(mail.sent.length,5);});
test('profile is isolated, optimistic version checked, privilege fields rejected',async()=>{const {env,db}=setup();const alice=await invitedLogin(env,db),bob=await invitedLogin(env,db,'bob@example.com');const headers={Cookie:alice.cookie,'X-CSRF-Token':alice.me.csrf};const input={name:'Alice',description:'My places',links:[],version:0};assert.equal((await accounts(req('api/profile','PATCH',{...input,curated:true},headers),env)).status,400);assert.equal((await accounts(req('api/profile','PATCH',input,headers),env)).status,200);assert.equal((await accounts(req('api/profile','PATCH',input,headers),env)).status,409);const b=await(await accounts(req('api/me','GET',undefined,{Cookie:bob.cookie}),env)).json();assert.equal(b.profile.name,'旅行者');assert.equal((await accounts(req('api/profile','PATCH',{...input,version:1},{Cookie:alice.cookie,'X-CSRF-Token':bob.me.csrf}),env)).status,403);});
test('Google uses state and PKCE; binding joins verified identity without duplicate users',async()=>{const {env,db}=setup();const alice=await invitedLogin(env,db);let r=await accounts(req('api/google/start','POST',{link:true},{Cookie:alice.cookie,'X-CSRF-Token':alice.me.csrf}),env);const u=new URL((await r.json()).url);assert.equal(u.searchParams.get('code_challenge_method'),'S256');let calls=0;const fetcher=async(url,options)=>{calls++;if(url.includes('/token')){assert(new URLSearchParams(options.body).get('code_verifier'));return Response.json({access_token:'test'})}return Response.json({sub:'google-alice',email:'alice@example.com',email_verified:true})};const callback='google/callback?state='+u.searchParams.get('state')+'&code=code';assert.equal((await accounts(req(callback),env,fetcher)).status,400);assert.equal(calls,0);r=await accounts(req(callback,'GET',undefined,{Cookie:alice.cookie+'; '+jar(r)}),env,fetcher);assert.equal(r.status,303);assert.equal(db.prepare('SELECT COUNT(*) n FROM creator_users').get().n,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM creator_identities').get().n,2);});
test('same email does not auto-link Google identity and unverified Google email fails',async()=>{const {env,db}=setup();await invitedLogin(env,db);for(const verified of [false,true]){const start=await accounts(req('api/google/start','POST',{}),env);const url=new URL((await start.json()).url);const response=await accounts(req('google/callback?state='+url.searchParams.get('state')+'&code=x','GET',undefined,{Cookie:jar(start)}),env,async u=>u.includes('/token')?Response.json({access_token:'x'}):Response.json({sub:'new-google',email:'alice@example.com',email_verified:verified}));assert.equal(response.status,verified?409:401);}assert.equal(db.prepare('SELECT COUNT(*) n FROM creator_identities').get().n,1);});
test('private media cannot be read by another account and enforces type/size',async()=>{const {env,db}=setup();const a=await invitedLogin(env,db),b=await invitedLogin(env,db,'bob@example.com');const headers={Cookie:a.cookie,'X-CSRF-Token':a.me.csrf,'Content-Type':'image/png'};const bytes=new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,0]);assert.equal((await accounts(req('api/media/avatar','POST',bytes,headers),env)).status,200);const download=await accounts(req('api/media/avatar','GET',undefined,{Cookie:a.cookie}),env);assert.deepEqual(new Uint8Array(await download.arrayBuffer()),bytes);assert.equal((await accounts(req('api/media/avatar','GET',undefined,{Cookie:b.cookie}),env)).status,404);assert.equal((await accounts(req('api/media/avatar','POST','<svg></svg>',headers),env)).status,413);assert.equal((await accounts(req('api/media/avatar','POST',new Uint8Array(256*1024+1),headers),env)).status,413);});
