const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
 const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const submissions=[];await page.route('**/api/recommendations',r=>{submissions.push(r.request().postDataJSON());return r.fulfill({status:submissions.length===1?502:201,json:submissions.length===1?{error:'temporary'}:{ok:true,id:submissions.at(-1).id}})});
 await page.goto('http://127.0.0.1:4173');await page.getByRole('button',{name:'推薦好地方',exact:true}).click();const form=page.locator('#recommendation-form');
 for(const [name,value] of Object.entries({country:'台灣',city:'花蓮',name:'讀者推薦',mapUrl:'https://maps.app.goo.gl/abc123',reason:'海岸散步',email:'reader@example.com'}))await form.locator(`[name=${name}]`).fill(value);
 await form.locator('[name=consent]').check();await page.getByRole('button',{name:'送出推薦',exact:true}).click();await page.getByText('暫時無法送出，輸入已保留，請稍後重試。').waitFor();assert.equal(await form.locator('[name=name]').inputValue(),'讀者推薦');await page.getByRole('button',{name:'送出推薦',exact:true}).click();await page.getByText(/已收到，謝謝你的推薦/).waitFor();assert.equal(submissions[0].id,submissions[1].id);assert.equal(await form.locator('[name=name]').inputValue(),'');await page.screenshot({path:'/tmp/pocket-recommendation-mobile.png',fullPage:true});await page.keyboard.press('Escape');assert.equal(await page.locator('#recommendation-dialog').isVisible(),false);
 await page.locator('#language').selectOption('en');await page.getByRole('button',{name:'Recommend a place',exact:true}).click();await page.getByRole('heading',{name:'Recommend a place',exact:true}).waitFor();await page.keyboard.press('Escape');
 const admin=await browser.newPage({viewport:{width:1280,height:950}});admin.on('pageerror',e=>errors.push(e.message));await admin.addInitScript(()=>sessionStorage.setItem('atlas-admin-token','test-editor'));
 let row={id:'11111111-1111-4111-a111-111111111111',name:'推薦景點',country:'台灣',city:'花蓮',category:'sights',map_url:'https://maps.app.goo.gl/abc123',reason:'<script>alert(1)</script>',email:'reader@example.com',created_at:new Date().toISOString(),status:'pending'},imports=[],expired=false;
 await admin.route('**/api/admin/**',r=>{const req=r.request(),url=new URL(req.url());if(expired)return r.fulfill({status:401,json:{error:'expired'}});
 if(url.pathname.endsWith('/recommendations')){if(req.method()==='PATCH')row.status=req.postDataJSON().status;if(req.method()==='DELETE')row=null;return r.fulfill({json:req.method()==='GET'?{items:row&&row.status===url.searchParams.get('status')?[row]:[],nextOffset:null}:{ok:true}});}
 if(url.pathname.endsWith('/destinations'))return r.fulfill({json:{items:[{id:'hualien',kind:'cities',name:'花蓮',english:'Hualien',parent:'台灣',parentEnglish:'Taiwan',sha:imports.length?'new-sha':'old-sha'}]}});
 if(url.pathname.endsWith('/search'))return r.fulfill({json:{items:[{pageId:123,title:'Qingshui Cliffs',description:'清水斷崖與太平洋',url:'http://127.0.0.1:4173/assets/hualien.jpg',artist:'Test photographer',license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',source:'https://commons.wikimedia.org/wiki/Special:Redirect/page/123'}]}});
 if(url.pathname.endsWith('/import')){imports.push(req.postDataJSON());return r.fulfill({status:imports.length===1?409:200,json:imports.length===1?{error:'conflict'}:{ok:true}});}return r.abort();});
 await admin.goto('http://127.0.0.1:4173/admin/tools.html');await admin.getByRole('heading',{name:'推薦景點'}).waitFor();assert.equal(await admin.locator('.recommendation script').count(),0);await admin.getByRole('button',{name:'已採納',exact:true}).click();await admin.getByText('目前沒有這個狀態的推薦。').waitFor();await admin.locator('#inbox-filter').selectOption('accepted');await admin.getByRole('heading',{name:'推薦景點'}).waitFor();await admin.getByRole('button',{name:'刪除',exact:true}).click();await admin.locator('#confirm-delete').click();await admin.getByText('推薦內容與 Email 已刪除。').waitFor();
 await admin.getByRole('button',{name:'自動搜圖候選',exact:true}).click();await admin.locator('#destination').selectOption('cities/hualien');await admin.getByRole('button',{name:'選擇這張照片'}).click();assert.equal(await admin.locator('#photo-alt').inputValue(),'清水斷崖與太平洋');await admin.screenshot({path:'/tmp/pocket-photo-candidates.png',fullPage:true});await admin.locator('#save-photo').click();await admin.locator('#tool-status').filter({hasText:'內容已被修改，請重新整理目的地後再選圖。'}).waitFor();await admin.getByRole('button',{name:'選擇這張照片'}).click();await admin.locator('#save-photo').click();await admin.locator('#tool-status').filter({hasText:/封面與授權已保存/}).waitFor();assert.equal(imports[0].expectedSha,'old-sha');assert.equal(imports[1].expectedSha,'new-sha');
 expired=true;await admin.locator('#tab-inbox').click();await admin.locator('#refresh-inbox').click();await admin.locator('#login').waitFor();assert.equal(await admin.locator('#workspace').isVisible(),false);assert.deepEqual(errors,[]);console.log('PASS recommendation failure/retry/idempotency, five-language UI entry, private inbox moderation, candidate selection, stale-content protection, atomic import UI and expired-session handling');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
