const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
 const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 let saved=0,used=0;await page.route('**/api/stats**',r=>{const req=r.request();if(req.method()==='POST'){const b=req.postDataJSON();if(b.action==='save')saved=1;if(b.action==='unsave')saved=0;if(b.action==='use')used=1;return r.fulfill({json:{saved,used,isSaved:!!saved}})}const ids=new URL(req.url()).searchParams.get('ids').split(',');return r.fulfill({json:{items:ids.map(list_id=>({list_id,saved,used}))}})});
 await page.goto('http://127.0.0.1:4173');await page.locator('.country-card').first().waitFor();
 assert.equal(await page.locator('#continents').getByText('亞洲',{exact:true}).count(),1);assert.ok(!(await page.locator('#continents').innerText()).includes('✨'));
 await page.locator('#language').selectOption('en');assert.ok(!(await page.locator('#continents').innerText()).includes('Asia Asia'));
 await page.waitForFunction(()=>[...document.querySelectorAll('.cover img')].some(i=>i.complete&&i.naturalWidth));const image=await page.locator('.cover img').first().evaluate(i=>({src:i.currentSrc,priority:i.fetchPriority}));assert.match(image.src,/media\/.*-480.webp/);assert.equal(image.priority,'high');
 await page.goto('http://127.0.0.1:4173/#/asia/taiwan');const stats=page.locator('.list-stats').first();await stats.locator('.stats-count').filter({hasText:'saved here'}).waitFor();await stats.locator('button').click();await stats.getByRole('button',{name:'Unsave',exact:true}).waitFor();assert.equal(await stats.locator('button').getAttribute('aria-pressed'),'true');await stats.locator('button').click();await stats.getByRole('button',{name:'Save here',exact:true}).waitFor();assert.equal(saved,0);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'/tmp/pocket-enhanced-mobile.png',fullPage:true});
 const admin=await browser.newPage({viewport:{width:1280,height:900}});admin.on('pageerror',e=>errors.push(e.message));await admin.addInitScript(()=>localStorage.setItem('decap-cms-user',JSON.stringify({backendName:'github',token:'test-editor'})));
 let secondCalls=0,imports=0;const photo=id=>({pageId:id,title:'Photo '+id,description:'海岸',url:'http://127.0.0.1:4173/assets/hualien.jpg',artist:'Author',license:'CC BY 4.0',licenseUrl:'https://creativecommons.org/licenses/by/4.0/',source:'https://commons.wikimedia.org/wiki/File:Example.jpg'});
 await admin.route('**/api/admin/**',r=>{const url=new URL(r.request().url());if(url.pathname.endsWith('/destinations'))return r.fulfill({json:{items:[{id:'test',kind:'cities',name:'Test',english:'Test',sha:'sha'}]}});if(url.pathname.endsWith('/notifications'))return r.fulfill({json:{configured:false,counts:{}}});if(url.pathname.endsWith('/recommendations'))return r.fulfill({json:{items:[]}});
 if(url.pathname.endsWith('/usage'))return r.fulfill({json:{day:'2026-09-29',observed:[{day:'2026-09-29',metric:'ai_attempts',value:2}],translation:null,note:'僅本站記錄'}});
 if(url.pathname.endsWith('/search')){if(url.searchParams.get('offset')==='50'){secondCalls++;if(secondCalls===1)return r.fulfill({status:502,json:{error:'temporary'}});return r.fulfill({json:{items:[photo(1),photo(2)],scanned:50,filtered:48,nextOffset:null}})}return r.fulfill({json:{items:[photo(1)],scanned:50,filtered:49,nextOffset:50}})}
 if(url.pathname.endsWith('/import-description')){const b=r.request().postDataJSON();if(b.mode==='info')return r.fulfill({json:{links:['https://maps.app.goo.gl/test'],description:'',sha:'sha'}});if(b.mode==='preview')return r.fulfill({json:{text:'',notice:'未取得清單原始說明'}});imports++;assert.equal(b.confirmed,true);assert.equal(b.method,'manual-copy');return r.fulfill({json:{ok:true}})}return r.abort()});
 await admin.goto('http://127.0.0.1:4173/admin/tools.html');await admin.locator('#workspace').waitFor();await admin.locator('#tab-photos').click();await admin.locator('#destination').selectOption('cities/test');await admin.locator('.photo-option').waitFor();await admin.locator('#more-photos').click();await admin.getByText('temporary',{exact:true}).waitFor();assert.equal(await admin.locator('.photo-option').count(),1);await admin.locator('#more-photos').click();await admin.waitForFunction(()=>document.querySelectorAll('.photo-option').length===2);assert.equal(await admin.locator('#more-photos').isVisible(),false);
 await admin.locator('#description-import summary').click();await admin.locator('#description-info').click();await admin.getByText('簡介目前空白。',{exact:true}).waitFor();await admin.locator('#description-preview').click();await admin.getByText('未取得清單原始說明',{exact:true}).waitFor();await admin.locator('#description-text').fill('這是經核對的原始清單說明');await admin.locator('#description-confirm').check();await admin.locator('#description-save').click();await admin.getByText('已保存說明與來源，等待網站發布。',{exact:true}).waitFor();assert.equal(imports,1);
 await admin.locator('#tab-usage').click();await admin.getByText(/AI 生成嘗試：2/).waitFor();await admin.getByText(/先前用量未知/).waitFor();await admin.screenshot({path:'/tmp/pocket-usage-desktop.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: localized tabs, responsive images, save/unsave, pagination retry/dedup, reviewed import, usage panel; no page errors.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
