const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
const page=await browser.newPage({viewport:{width:390,height:844},colorScheme:'dark'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4173');await page.locator('.country-card').first().waitFor();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
await page.locator('#theme').selectOption('light');await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
await page.locator('#language').selectOption('en');await page.getByRole('link',{name:'Explore Taiwan',exact:true}).click();await page.getByRole('heading',{name:'Next stop: Taiwan'}).waitFor();assert.equal(await page.locator('html').getAttribute('lang'),'en');assert.ok((await page.locator('.card-description').first().textContent()).includes('Yilan'));
await page.reload();await page.getByRole('heading',{name:'Next stop: Taiwan'}).waitFor();await page.locator('#language').selectOption('zh-Hans');await page.getByRole('heading',{name:'宜兰县'}).waitFor();
await page.locator('#language').selectOption('ja');await page.getByRole('heading',{name:'宜蘭県',exact:true}).waitFor();await page.locator('#language').selectOption('ko');await page.getByRole('heading',{name:'이란현',exact:true}).waitFor();await page.locator('#language').selectOption('zh-Hans');
await page.locator('#theme').selectOption('dark');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/pocket-dark-mobile.png',fullPage:true});
const data=JSON.parse(fs.readFileSync('dist/data.json'));const city=data.cities.find(c=>c.id==='hualien');city.article='第一天\n\n<script>alert("unsafe")</script>';city.articleEn='Day one\n\nA slow walk by the sea.';city.myMap='https://www.google.com/maps/d/viewer?mid=example_123456789';
await page.route('**/data.json',r=>r.fulfill({json:data}));await page.reload();await page.locator('#language').selectOption('en');await page.locator('.city-card').filter({hasText:'Hualien'}).getByRole('link',{name:'My Maps →'}).click();await page.getByText('A slow walk by the sea.').waitFor();assert.equal(await page.locator('iframe').count(),0);
await page.route('https://www.google.com/maps/d/embed**',r=>r.fulfill({body:'<p>Test map</p>',contentType:'text/html'}));await page.getByRole('button',{name:'Load interactive map'}).click();assert.equal(await page.locator('iframe').getAttribute('src'),'https://www.google.com/maps/d/embed?mid=example_123456789');
await page.reload();await page.getByText('A slow walk by the sea.').waitFor();await page.locator('#language').selectOption('zh-Hant');assert.equal(await page.locator('.story-prose script').count(),0);assert.ok((await page.locator('.story-prose').innerText()).includes('<script>'));
await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'/tmp/pocket-dark-story.png',fullPage:true});const updated=structuredClone(data);updated.version='next-build';updated.cities.find(c=>c.id==='hualien').name='更新後花蓮';await page.route('**/data.json',r=>r.fulfill({json:updated}));await page.evaluate(()=>dispatchEvent(new Event('focus')));await page.locator('#content-update').waitFor();await page.locator('#refresh-content').click();await page.getByRole('heading',{name:'更新後花蓮',exact:true}).waitFor();assert.equal(await page.locator('#content-update').isVisible(),false);assert.deepEqual(errors,[]);console.log('PASS themes, persistence, five languages, mobile layout, city article routes, safe text and opt-in My Maps embeds and stale-page update prompts');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
