const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{
 const {setup}=await import('./helpers/accounts-env.mjs');const {accounts}=await import('../worker/accounts.mjs');
 const {generateKeyPair,exportJWK,SignJWT}=await import('jose');const {privateKey,publicKey}=await generateKeyPair('RS256');const jwk={...await exportJWK(publicKey),kid:'browser-key',alg:'RS256'};
 const {env,db}=setup();Object.assign(env,{AUTH_PROVIDER:'firebase',FIREBASE_PROJECT_ID:'browser-project',FIREBASE_API_KEY:'test',FIREBASE_APP_ID:'test'});db.prepare('INSERT INTO creator_invitations(email) VALUES(?)').run('alice@example.com');
 const t=await new SignJWT({email:'alice@example.com',email_verified:true,auth_time:Math.floor(Date.now()/1000),firebase:{sign_in_provider:'password'}}).setProtectedHeader({alg:'RS256',kid:'browser-key'}).setIssuer('https://securetoken.google.com/browser-project').setAudience('browser-project').setSubject('alice').setIssuedAt().setExpirationTime('1h').sign(privateKey);
 const fetcher=async url=>url.includes('/jwk/')?Response.json({keys:[jwk]}):Response.json({users:[{localId:'alice',email:'alice@example.com',emailVerified:true}]});
 const browser=await chromium.launch({channel:'chrome',headless:true});try{const context=await browser.newContext({locale:'zh-TW'});
 await context.route('https://accounts.test/**',async route=>{const r=route.request();const response=await accounts(new Request(r.url(),{method:r.method(),headers:await r.allHeaders(),...(r.postDataBuffer()?{body:r.postDataBuffer()}: {})}),env,fetcher);await route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:Buffer.from(await response.arrayBuffer())});});
 await context.route('https://www.gstatic.com/firebasejs/12.4.0/firebase-app.js',r=>r.fulfill({contentType:'application/javascript',body:'export function initializeApp(config){return config}'}));
 // Browser SDK facade only: test UI orchestration; provider/network acceptance remains a live pre-release check.
 await context.route('https://www.gstatic.com/firebasejs/12.4.0/firebase-auth.js',r=>r.fulfill({contentType:'application/javascript',body:`const auth={currentUser:null};const user={emailVerified:false,getIdToken:async()=>${JSON.stringify(t)}};export const inMemoryPersistence={};export const getAuth=()=>auth;export const setPersistence=async()=>{};export class GoogleAuthProvider{};export const signOut=async()=>{auth.currentUser=null};export const reload=async u=>{u.emailVerified=true};export const signInWithPopup=async()=>{user.emailVerified=true;auth.currentUser=user;return {user}};export const signInWithEmailAndPassword=signInWithPopup;export const createUserWithEmailAndPassword=async()=>{auth.currentUser=user;return {user}};export const sendEmailVerification=async()=>{await new Promise(r=>setTimeout(r,500));if(!window.mailRetried){window.mailRetried=true;throw Error('mail failure')}};export const sendPasswordResetEmail=async()=>{};`}));
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('https://accounts.test/account/');
 await page.locator('#email').fill('alice@example.com');await page.locator('#password').fill('testing123');await page.locator('#register').click();await page.waitForFunction(()=>document.querySelector('#auth-feedback').textContent.includes('正在寄送'));assert.equal(await page.locator('#register').isDisabled(),true);await page.waitForFunction(()=>document.querySelector('#auth-feedback').textContent.includes('寄送失敗'));assert.equal(await page.locator('#verify').isVisible(),true);await page.locator('#resend-verification').click();await page.waitForFunction(()=>document.querySelector('#auth-feedback').textContent.includes('已重新寄出'));await page.locator('#check-verification').click();await page.waitForURL('https://accounts.test/');await page.goto('https://accounts.test/account/');await page.locator('#editor').waitFor({state:'visible'});
 await page.locator('#name').fill('Alice');await page.locator('#description').fill('<b>我的口袋世界</b>');for(const [label,url] of [['Blog','https://example.com'],['Video','https://example.org']]){await page.locator('#add-link').click();await page.locator('[data-label]').last().fill(label);await page.locator('[data-url]').last().fill(url);}assert.equal(await page.locator('#save-state').getAttribute('data-state'),'dirty');await page.locator('#avatar').setInputFiles({name:'avatar.png',mimeType:'image/png',buffer:await require('sharp')({create:{width:16,height:16,channels:4,background:'#225588'}}).png().toBuffer()});await page.waitForFunction(()=>document.querySelector('#preview-avatar').naturalWidth>0);await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('已儲存並公開'));
 assert.equal(await page.locator('#save-state').getAttribute('data-state'),'saved');await page.reload();await page.locator('#editor').waitFor({state:'visible'});assert.equal(await page.locator('#links').inputValue(),'Blog | https://example.com/\nVideo | https://example.org/');assert.equal(await page.locator('#preview-description').textContent(),'<b>我的口袋世界</b>');
 await page.locator('#preview-toggle').click();assert.equal(await page.locator('#profile-form').isVisible(),false);assert.equal(await page.locator('#preview-links a').count(),2);await page.locator('#preview-toggle').click();await page.locator('#account-language').selectOption('en');assert.equal(await page.locator('#save').textContent(),'Save & publish');await page.reload();await page.locator('#editor').waitFor({state:'visible'});assert.equal(await page.locator('#save').textContent(),'Save & publish');await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/pocket-firebase-profile-mobile.png',fullPage:false});
 await page.locator('#profile-menu summary').click();await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});await page.screenshot({path:'/tmp/pocket-login-mobile.png'});await page.emulateMedia({colorScheme:'dark'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');assert.equal(await page.locator('#login').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(28, 46, 39)');await page.screenshot({path:'/tmp/pocket-login-dark.png',animations:'disabled'});await page.emulateMedia({colorScheme:'light'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');await page.evaluate(()=>localStorage.setItem('atlas-theme','dark'));await page.reload();await page.locator('#google').waitFor({state:'visible'});assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.locator('#google').click();await page.waitForURL('https://accounts.test/');await page.goto('https://accounts.test/account/');await page.locator('#editor').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('#preview-avatar').naturalWidth>0);assert.equal(db.prepare('SELECT COUNT(*) n FROM creator_users').get().n,1);assert.deepEqual(errors,[]);console.log('PASS Firebase UI with mocked SDK: registration, verification, Google sign-in, private profile save/reload, mobile, logout');
 }finally{await browser.close();db.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
