const {chromium}=require('playwright');const fs=require('node:fs/promises');const assert=require('node:assert/strict');const path=require('node:path');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:390,height:844}});let sent=[];
 await p.route('https://launch.test/**',async route=>{const u=new URL(route.request().url());if(u.pathname==='/api/recommendations'){sent.push(JSON.parse(route.request().postData()));return route.fulfill({json:{ok:true}});}try{const file=path.join(process.cwd(),'dist',u.pathname==='/'?'index.html':u.pathname);await route.fulfill({body:await fs.readFile(file),contentType:({'.html':'text/html','.js':'application/javascript','.mjs':'application/javascript','.css':'text/css','.json':'application/json'})[path.extname(file)]||'application/octet-stream'});}catch{await route.fulfill({status:404,body:''});}});
 await p.goto('https://launch.test/contact.html?type=account');await p.locator('#reply-email').fill('tester@example.test');await p.locator('#message').fill('Please remove my test account');await p.locator('#consent').check();await p.getByRole('button',{name:'送出訊息'}).click();await p.getByRole('status').filter({hasText:'訊息已保存'}).waitFor();assert.equal(sent.length,1);assert.match(sent[0].name,/帳號刪除/);assert.equal(sent[0].email,'tester@example.test');assert.equal(sent[0].consent,true);
 await p.goto('https://launch.test/');await p.locator('.catalog-card').first().waitFor();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await p.locator('.editorial-hero').evaluate(e=>Math.round(e.getBoundingClientRect().height)),370);assert.equal(await p.locator('footer a[href="./privacy.html"]').count(),1);assert.equal(await p.locator('.brand-sub').count(),0);assert(!await p.locator('#cards').textContent().then(s=>s.includes('Ttt')));await p.screenshot({path:'/tmp/launch128-mobile.png',fullPage:true});
 await p.goto('https://launch.test/#/search?q=披薩');await p.locator('.search-note').waitFor();assert.match(await p.locator('.search-note').textContent(),/不會自動匯入/);
 // Module-driven admin interface with mock API; no production mutation.
 await p.setContent('<main id="test-root"></main>');await p.evaluate(async()=>{const {renderListsPanel}=await import('/admin/lists-panel.js');window.patch=[];let hidden=0;renderListsPanel(document.getElementById('test-root'),async(path,options)=>{if(options){window.patch.push(JSON.parse(options.body));hidden=1;return {ok:true};}return {items:[{id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',title:'<b>Test</b>',author:'Writer',destination:'Taipei',moderated:hidden,reason:'Review',revision:hidden,public:!hidden}],nextOffset:null};});});await p.getByRole('button',{name:'下架清單',exact:true}).click();await p.getByRole('textbox',{name:'管理原因'}).fill('缺少授权');await p.getByRole('button',{name:'確認下架'}).click();await p.getByRole('button',{name:'恢復清單',exact:true}).waitFor();assert.equal(await p.locator('h3 b').count(),0);assert.equal((await p.evaluate(()=>window.patch))[0].hidden,true);assert.equal((await p.evaluate(()=>window.patch))[0].reason,'缺少授权');console.log('PASS contact confirmation, mobile hero/layout, eligibility, search explanation and moderation UI');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
