import test from 'node:test';import assert from 'node:assert/strict';import {createHandler} from '../worker/index.mjs';
const env={GITHUB_CLIENT_ID:'test-client',GITHUB_CLIENT_SECRET:'test-secret',GITHUB_REPO:'owner/repo',SITE_ORIGIN:'https://owner.github.io'};
const start=async()=>createHandler()(new Request('https://auth.example/auth?provider=github&site_id=owner.github.io'),env);
async function callback(mock,stateOverride){const r=await start();const state=new URL(r.headers.get('location')).searchParams.get('state');return createHandler(mock)(new Request('https://auth.example/callback?code=test-code&state='+(stateOverride||state),{headers:{cookie:r.headers.get('set-cookie').split(';')[0]}}),env);}
test('unconfigured auth is unavailable without exposing secrets',async()=>{assert.equal((await createHandler()(new Request('https://auth.example/auth'),{})).status,503);});
test('auth generates CSRF state and secure HttpOnly cookie, limited public repo scope',async()=>{const r=await start();assert.equal(r.status,302);const u=new URL(r.headers.get('location'));assert.equal(u.origin,'https://github.com');assert.equal(u.searchParams.get('scope'),'public_repo');assert.match(u.searchParams.get('state'),/^[a-f0-9]{64}$/);assert.match(r.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Lax/);assert.equal((await createHandler()(new Request('https://auth.example/auth?site_id=evil.test'),env)).status,400);});
test('missing or mismatched state is rejected before token exchange',async()=>{let called=false;const r=await callback(()=>{called=true},'a'.repeat(64));assert.equal(r.status,403);assert.equal(called,false);assert.equal((await createHandler()(new Request('https://auth.example/callback?code=x&state='+'b'.repeat(64)),env)).status,403);});
test('read-only GitHub account cannot receive CMS token',async()=>{let calls=0;const r=await callback(async()=>Response.json(calls++===0?{access_token:'secret-token'}:{permissions:{push:false}}));assert.equal(r.status,403);assert.ok(!(await r.text()).includes('secret-token'));});
test('authorized token is posted only to configured origin and opener; cookie cleared',async()=>{let calls=0;const r=await callback(async()=>Response.json(calls++===0?{access_token:'test-token'}:{permissions:{push:true}}));const html=await r.text();assert.equal(r.status,200);assert.match(html,/event\.origin!==origin/);assert.match(html,/event\.source!==window\.opener/);assert.ok(html.includes('https://owner.github.io'));assert.ok(!html.includes("postMessage('*'"));assert.match(r.headers.get('set-cookie'),/Max-Age=0/);assert.match(r.headers.get('Content-Security-Policy'),/default-src 'none'/);});
test('upstream failures and permission checks fail closed',async()=>{assert.equal((await callback(async()=>{throw Error('secret upstream detail')})).status,502);assert.equal((await callback(async()=>Response.json({error:'bad_code'}))).status,401);assert.equal((await createHandler()(new Request('https://auth.example/auth',{method:'POST'}),env)).status,405);});
