import test from 'node:test';import assert from 'node:assert/strict';
import {setup} from './helpers/accounts-env.mjs';import {accounts,digest} from '../worker/accounts.mjs';import {validatePilotList} from '../worker/pilot-api.mjs';
const origin='https://pilot.test';
export async function fixture(){const {env,db}=setup();for(const id of ['alice','bob']){db.prepare('INSERT INTO creator_users(id,primary_email,created_at) VALUES(?,?,0)').run(id,id+'@example.com');db.prepare('INSERT INTO creator_profiles(user_id,creator_id,name,description,links,updated_at) VALUES(?,?,?,?,?,0)').run(id,id+'-creator',id,'Original bio','[]');const token=(id==='alice'?'a':'b').repeat(64);db.prepare('INSERT INTO creator_sessions(hash,user_id,csrf,expires_at) VALUES(?,?,?,?)').run(await digest(token),id,id+'-csrf',Math.floor(Date.now()/1000)+3600);}return {env,db};}
const req=(path,who,method='GET',data)=>new Request(origin+'/account/api/'+path,{method,headers:{...(who?{Cookie:'__Host-atlas_session='+(who==='alice'?'a':'b').repeat(64),'X-CSRF-Token':who+'-csrf'}:{}),...(method==='GET'?{}:{Origin:origin,'Content-Type':'application/json'})},...(data?{body:JSON.stringify(data)}:{})});
const entry={title:'Coffee walk',description:'My favourite places',url:'https://maps.app.goo.gl/example',destination:'Taipei',tags:['Coffee']};
test('pilot snapshots, two owners, feed, unpublish and draft privacy',async()=>{const {env,db}=await fixture();const call=(...args)=>accounts(req(...args),env);
 assert.equal((await call('pilot/lists',null,'POST',entry)).status,401);
 let result=await(await call('pilot/lists','alice','POST',entry)).json();const id=result.id;
 assert.equal((await call('pilot/lists/'+id+'/publish','alice','POST',{version:1})).status,409);
 assert.equal((await call('pilot/lists/'+id,'bob','PATCH',{...entry,version:1})).status,404);
 assert.equal((await call('pilot/profile/publish','alice','POST',{version:0})).status,200);
 assert.equal((await call('pilot/lists/'+id+'/publish','alice','POST',{version:1})).status,200);
 let feed=await(await call('pilot/feed')).json();assert.equal(feed.items.length,1);assert.equal(feed.items[0].creator.name,'alice');assert(!JSON.stringify(feed).includes('@example.com'));
 assert.equal((await call('pilot/lists/'+id,'alice','PATCH',{...entry,title:'Private edit',version:2})).status,200);
 feed=await(await call('pilot/feed')).json();assert.equal(feed.items[0].title,'Coffee walk');
 assert.equal((await call('pilot/lists/'+id+'/publish','alice','POST',{version:2})).status,409);
 db.prepare('UPDATE creator_profiles SET description=?,version=1 WHERE user_id=?').run('Private bio','alice');
 const profile=await(await call('pilot/creators/alice-creator')).json();assert.equal(profile.description,'Original bio');
 assert.equal((await call('pilot/profile/publish','alice','POST',{version:0})).status,409);
 await call('pilot/profile/publish','bob','POST',{version:0});result=await(await call('pilot/lists','bob','POST',{...entry,title:'Bob walk'})).json();await call('pilot/lists/'+result.id+'/publish','bob','POST',{version:1});assert.equal((await(await call('pilot/feed')).json()).items.length,2);
 await call('pilot/profile/unpublish','alice','POST');assert.equal((await call('pilot/creators/alice-creator')).status,404);assert.equal((await(await call('pilot/feed')).json()).items.length,1);
 await call('pilot/profile/publish','alice','POST',{version:1});await call('pilot/lists/'+id+'/unpublish','alice','POST',{version:3});assert.equal((await(await call('pilot/feed')).json()).items.length,1);
 db.prepare('UPDATE creator_users SET suspended=1 WHERE id=?').run('bob');assert.equal((await(await call('pilot/feed')).json()).items.length,0);db.close();
});
test('public media snapshots preserve draft privacy and disappear when hidden',async()=>{const {env,db}=await fixture();const bytes=new Uint8Array([1,2,3]);db.prepare('INSERT INTO creator_media VALUES(?,?,?,?,0)').run('alice','avatar','image/webp',bytes);await accounts(req('pilot/profile/publish','alice','POST',{version:0}),env);db.prepare('UPDATE creator_media SET bytes=?').run(new Uint8Array([4,5,6]));let r=await accounts(req('pilot/creators/alice-creator/avatar'),env);assert.deepEqual(new Uint8Array(await r.arrayBuffer()),bytes);await accounts(req('pilot/profile/unpublish','alice','POST'),env);assert.equal((await accounts(req('pilot/creators/alice-creator/avatar'),env)).status,404);db.close();});
test('pilot validation, pagination, CSRF and ownership fields',async()=>{const {env,db}=await fixture();for(const url of ['javascript:alert(1)','http://example.com','https://user:pass@example.com'])assert.throws(()=>validatePilotList({...entry,url}));assert.throws(()=>validatePilotList({...entry,user_id:'bob'}));assert.equal((await accounts(new Request(origin+'/account/api/pilot/profile/publish',{method:'POST',headers:{Origin:'https://evil.test'}}),env)).status,403);assert.equal((await accounts(req('pilot/feed?page=-1'),env)).status,400);assert.equal((await accounts(req('pilot/profile/publish','alice'),env)).status,404);db.close();});
test('cover snapshots only expose published bytes and exclude data from feed',async()=>{const {env,db}=await fixture();const call=(...args)=>accounts(req(...args),env);const bytes=Buffer.from('RIFF0000WEBPtest');const cover='data:image/webp;base64,'+bytes.toString('base64');assert.throws(()=>validatePilotList({...entry,cover:'data:image/svg+xml;base64,abcd'}));const saved=await(await call('pilot/lists','alice','POST',{...entry,cover})).json();assert.equal((await call('pilot/covers/'+saved.id)).status,404);await call('pilot/profile/publish','alice','POST',{version:0});await call('pilot/lists/'+saved.id+'/publish','alice','POST',{version:1});const feed=await(await call('pilot/feed')).json();assert.equal(feed.items[0].cover,undefined);assert(feed.items[0].coverUrl.endsWith(saved.id));assert.deepEqual(Buffer.from(await(await call('pilot/covers/'+saved.id)).arrayBuffer()),bytes);await call('pilot/lists/'+saved.id,'alice','PATCH',{...entry,version:2});assert.equal((await call('pilot/covers/'+saved.id)).status,200);await call('pilot/profile/unpublish','alice','POST');assert.equal((await call('pilot/covers/'+saved.id)).status,404);db.close();});
test('attribution defaults and source validation',()=>{assert.equal(validatePilotList(entry).role,'author');assert.equal(validatePilotList({...entry,role:'curator'}).role,'curator');assert.throws(()=>validatePilotList({...entry,role:'admin'}));assert.throws(()=>validatePilotList({...entry,role:'sharer'}));assert.throws(()=>validatePilotList({...entry,role:'sharer',sourceName:'Google',sourceUrl:'javascript:alert(1)'}));const shared=validatePilotList({...entry,role:'sharer',sourceName:'Google Maps',sourceUrl:'https://maps.google.com'});assert.equal(shared.sourceName,'Google Maps');});

test('creator directory only exposes published, unsuspended snapshots',async()=>{const {env,db}=await fixture();const read=async()=> (await accounts(req('pilot/creators'),env)).json();assert.deepEqual((await read()).items,[]);await accounts(req('pilot/profile/publish','alice','POST',{version:0}),env);assert.equal((await read()).items[0].name,'alice');assert(!JSON.stringify(await read()).includes('@example.com'));db.prepare('UPDATE creator_users SET suspended=1 WHERE id=?').run('alice');assert.deepEqual((await read()).items,[]);assert.equal((await accounts(req('pilot/creators?page=-1'),env)).status,400);db.close();});

test('saving a list queues background parsing, including link changes; other owners cannot queue changes',async()=>{const {env,db}=await fixture();const result=await(await accounts(req('pilot/lists','alice','POST',entry),env)).json();assert.equal(db.prepare('SELECT state FROM saved_map_places WHERE source_url=?').get(entry.url).state,'pending');const changed='https://maps.app.goo.gl/updated';assert.equal((await accounts(req('pilot/lists/'+result.id,'bob','PATCH',{...entry,url:changed,version:1}),env)).status,404);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM saved_map_places').get().n,1);assert.equal((await accounts(req('pilot/lists/'+result.id,'alice','PATCH',{...entry,url:changed,version:1}),env)).status,200);assert.equal(db.prepare('SELECT state FROM saved_map_places WHERE source_url=?').get(changed).state,'pending');db.close();});
