const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const {setup}=await import('./helpers/accounts-env.mjs');const {accounts,digest}=await import('../worker/accounts.mjs');const {env,db}=setup();const browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];
try{const contexts=[];for(const name of ['Alice','Bob']){const token=(name==='Alice'?'a':'b').repeat(64);db.prepare('INSERT INTO creator_users(id,primary_email,created_at) VALUES(?,?,0)').run(name,name+'@example.com');db.prepare('INSERT INTO creator_profiles(user_id,creator_id,name,description,links,updated_at) VALUES(?,?,?,?,?,0)').run(name,name+'-page',name,'My places','[]');db.prepare('INSERT INTO creator_sessions(hash,user_id,csrf,expires_at) VALUES(?,?,?,?)').run(await digest(token),name,name+'csrf',Math.floor(Date.now()/1000)+3600);
 const c=await browser.newContext({locale:'zh-TW'});await c.addCookies([{name:'__Host-atlas_session',value:token,domain:'pilot.test',path:'/',secure:true,httpOnly:true,sameSite:'Lax'}]);await c.route('https://pilot.test/**',async route=>{const r=route.request();const response=await accounts(new Request(r.url(),{method:r.method(),headers:await r.allHeaders(),...(r.postDataBuffer()?{body:r.postDataBuffer()}: {})}),env);await route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:Buffer.from(await response.arrayBuffer())});});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));contexts.push({c,p,name});
 await p.goto('https://pilot.test/account/community#manage');await p.locator('#reset').waitFor();assert.equal(await p.locator('#list-form').isVisible(),false);await p.locator('#reset').click();assert.equal(await p.locator('#role').inputValue(),'author');await p.locator('#cover-alt').fill('Photo fallback');assert.equal(await p.locator('#live-card .cover-placeholder').textContent(),'Photo fallback');await p.locator('#title').fill(name+' coffee walk');await p.locator('#description').fill('<script>not executed</script> My favourite cafes.');await p.locator('#url').fill('https://maps.app.goo.gl/example');await p.locator('#destination').fill('Taipei');await p.locator('#tags').fill('咖啡, 散步');await p.locator('#cover').setInputFiles({name:'cover.png',mimeType:'image/png',buffer:await require('sharp')({create:{width:100,height:60,channels:4,background:'#559988'}}).png().toBuffer()});await p.waitForFunction(()=>document.querySelector('#live-card img'));await p.locator('#list-form button.primary').click();await p.waitForFunction(()=>document.querySelector('#draft-state').textContent.includes('已儲存'));await p.locator('#back-lists').click();await p.locator('#own-cards article').waitFor();p.on('dialog',d=>d.accept());await p.screenshot({path:'/tmp/pocket-studio-'+name+'.png',fullPage:true});
}
const {p:alice}=contexts[0],{p:bob}=contexts[1];await alice.goto('https://pilot.test/account/community');await alice.locator('#cards article').nth(1).waitFor();assert.equal(await alice.locator('#cards article').count(),2);assert.equal(await alice.locator('#account-nav').textContent(),'編輯個人資料');assert.equal(await alice.locator('.card-link').count(),0);assert.equal(await alice.locator('#cards .card-main').count(),2);await alice.locator('#cards .author a').filter({hasText:'Bob'}).click();await alice.locator('#creator h1').waitFor();assert.equal(await alice.locator('#creator h1').textContent(),'Bob');assert.equal(await alice.locator('#cards article').count(),1);
await bob.goto('https://pilot.test/account/community#manage');assert.equal(await bob.locator('#own-cards article').count(),1);assert.match(await bob.locator('#own-cards').textContent(),/Bob coffee walk/);await bob.locator('#own-cards button').click();await bob.locator('#visibility').selectOption('hidden');await bob.locator('#list-form button.primary').click();await bob.waitForFunction(()=>document.querySelector('#draft-state').textContent.includes('已儲存'));await bob.locator('#user-menu summary').click();await bob.locator('#logout').click();await bob.waitForURL('**/account/');assert.equal(db.prepare("SELECT COUNT(*) n FROM creator_sessions WHERE user_id='Bob'").get().n,0);
await alice.goto('https://pilot.test/account/community');await alice.locator('#cards article').waitFor();assert.equal(await alice.locator('#cards article').count(),1);await alice.setViewportSize({width:390,height:844});assert(await alice.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await alice.screenshot({path:'/tmp/pocket-pilot-mobile.png'});await alice.setViewportSize({width:1280,height:900});await alice.screenshot({path:'/tmp/pocket-pilot-desktop.png'});assert.deepEqual(errors,[]);console.log('PASS two-account publish/feed/profile/unpublish isolation, escaped content, mobile layout');
}finally{await browser.close();db.close();}})().catch(e=>{console.error(e);process.exitCode=1});
