const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,channel:'chrome'});try{
const p=await b.newPage({viewport:{width:1200,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));let posts=0,fail=false;
const counts={'cities/test/food':2,'cities/test/sights':3,'cities/test/myMap':4,'cities/shared/food':7,'themes/guide/link':5,'themes/guide/myMap':9};
await p.route('**/data.json',r=>r.fulfill({json:{continents:[{id:'asia',name:'亞洲',published:true,order:1}],countries:[{id:'taiwan',continent:'asia',name:'台灣',published:true,order:1}],cities:[{id:'test',country:'taiwan',name:'測試城市',published:true,order:1,food:'https://maps.app.goo.gl/testfood',sights:'https://maps.app.goo.gl/testsights',myMap:'https://www.google.com/maps/d/viewer?mid=abcdefghijk123',article:'旅程內容'},{id:'shared',country:'taiwan',name:'共用清單',published:true,order:2,food:'https://maps.app.goo.gl/shared',sights:'https://maps.app.goo.gl/shared'}],themes:[{id:'guide',name:'主題遊記',published:true,order:1,link:'https://maps.app.goo.gl/guide',myMap:'https://www.google.com/maps/d/viewer?mid=abcdefghijk123'}]}}));
await p.route('**/api/stats**',r=>{if(r.request().method()==='POST'){posts++;const {id}=r.request().postDataJSON();counts[id]++;return r.fulfill({json:{used:counts[id]}})}if(fail)return r.fulfill({status:503,json:{error:'unavailable'}});const ids=new URL(r.request().url()).searchParams.get('ids').split(',');return r.fulfill({json:{items:ids.map(list_id=>({list_id,used:counts[list_id]}))}})});
await p.goto('http://127.0.0.1:4173/#/asia/taiwan');await p.getByText('人氣 9',{exact:true}).waitFor();await p.getByText('人氣 7',{exact:true}).waitFor();assert.equal(await p.locator('.list-stats').count(),2);assert.equal(await p.locator('.list-stats details,.list-stats summary,.list-stats[title]').count(),0);
const card=p.locator('.destination-card').first();assert.equal(await card.locator('.card-body>*:last-child').getAttribute('class'),'list-stats');await card.locator('a[target=_blank]').first().evaluate(a=>a.addEventListener('click',e=>e.preventDefault()));await card.locator('a[target=_blank]').first().click();await p.getByText('人氣 10',{exact:true}).waitFor();await card.locator('a[target=_blank]').first().click();assert.equal(posts,1);
await p.locator('#language').selectOption('en');await p.getByText('Popularity 10',{exact:true}).waitFor();await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:'/tmp/pocket-popularity-mobile.png',fullPage:true});
await p.goto('http://127.0.0.1:4173/#/themes');await p.getByText('Popularity 14',{exact:true}).waitFor();await p.locator('.story-link').click();await p.locator('#story .list-stats').getByText('Popularity 14',{exact:true}).waitFor();assert.equal(await p.locator('.story-body>*:last-child').getAttribute('class'),'list-stats');
fail=true;await p.reload();await p.locator('#story .stats-count').getByText('Popularity —',{exact:true}).waitFor();assert.deepEqual(errors,[]);console.log('PASS aggregated card totals, shared URL deduplication, click updates, no duplicate labels/details, last-child placement, theme article, languages and failure state');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
