import test from 'node:test';import assert from 'node:assert/strict';
import {setup} from './helpers/accounts-env.mjs';
import {enqueueSources,processPlaces,readSaved,sourceURL,parseMyMaps} from '../worker/saved-places.mjs';
const source='https://maps.app.goo.gl/persistTest';
const list=(name='Pizza',total=1)=>{const row=[];row[4]='List';row[8]=[[null,[null,null,null,null,null,[null,null,24,121]],name,'Nice']];row[12]=total;return JSON.stringify([row]);};
const provider=()=>{let calls=0;return {fetcher:async url=>{calls++;return new Response(url.includes('getlist')?list():'<a href="/maps/preview/entitylist/getlist?id=test">Data</a>');},calls:()=>calls};};
test('persistent snapshots survive new readers and do not refetch for visitors',async()=>{const {env,db}=setup(),p=provider();await enqueueSources(env,[source]);assert.equal((await readSaved(env,source)).saved,false);await processPlaces(env,p.fetcher);for(let i=0;i<10;i++){const row=await readSaved(env,source);assert.equal(row.state,'ready');assert.equal(row.places[0].name,'Pizza');}await enqueueSources(env,[source]);await processPlaces(env,p.fetcher);assert.equal(p.calls(),2);db.close();});
test('failed refresh preserves saved places and respects retry backoff',async()=>{const {env,db}=setup(),p=provider();await enqueueSources(env,[source]);await processPlaces(env,p.fetcher);await enqueueSources(env,[source],{refresh:true});assert.equal((await readSaved(env,source)).places[0].name,'Pizza');let failedCalls=0;const unavailable=async()=>{failedCalls++;throw Error('Offline')};await processPlaces(env,unavailable);const row=await readSaved(env,source);assert.equal(row.state,'failed');assert.equal(row.saved,true);assert.equal(row.places[0].name,'Pizza');await processPlaces(env,unavailable);assert.equal(failedCalls,1);db.close();});
test('changed link creates separate data; simultaneous workers claim one job',async()=>{const {env,db}=setup(),p=provider();await enqueueSources(env,[source,'https://maps.app.goo.gl/other']);await Promise.all([processPlaces(env,p.fetcher,1),processPlaces(env,p.fetcher,1)]);await processPlaces(env,p.fetcher,2);assert.equal(db.prepare("SELECT COUNT(*) AS n FROM saved_map_places WHERE state='ready'").get().n,2);assert.equal(p.calls(),4);db.close();});
test('partial update does not replace complete saved snapshot',async()=>{const {env,db}=setup(),p=provider();await enqueueSources(env,[source]);await processPlaces(env,p.fetcher);await enqueueSources(env,[source],{refresh:true});await processPlaces(env,async url=>new Response(url.includes('getlist')?list('Partial',3):'<a href="/maps/preview/entitylist/getlist?id=test">Data</a>'));assert.equal((await readSaved(env,source)).places[0].name,'Pizza');db.close();});
test('KML parsing decodes text, removes duplicate points and excludes paths',()=>{const xml='<kml><Document><Placemark><name><![CDATA[Ke\'e & Coast]]></name><Point><coordinates>-159,22,0</coordinates></Point><ExtendedData><Data name="地址"><value>Beach &amp; road</value></Data></ExtendedData></Placemark><Placemark><name><![CDATA[Ke\'e & Coast]]></name><Point><coordinates>-159,22,0</coordinates></Point></Placemark><Placemark><name>Route</name><LineString><coordinates>-159,22</coordinates></LineString></Placemark></Document></kml>';const result=parseMyMaps(xml);assert.equal(result.places.length,1);assert.equal(result.places[0].address,'Beach & road');assert.ok(result.places[0].photo);assert.equal(sourceURL('https://www.google.com/maps/d/embed?mid=123456789abcdef'),'https://www.google.com/maps/d/viewer?mid=123456789abcdef');assert.equal(sourceURL('https://evil.test/maps/x'),null)});

test('Google background jobs are claimed once and persist results with lease validation',async()=>{const {claimGoogleJobs,completeGoogleJob}=await import('../worker/saved-places.mjs');const {env,db}=setup();await enqueueSources(env,[source]);await processPlaces(env,()=>{throw Error('Worker must not fetch Google')},2,{myMapsOnly:true});assert.equal((await readSaved(env,source)).state,'pending');const first=await claimGoogleJobs(env),second=await claimGoogleJobs(env);assert.equal(first.jobs.length,1);assert.equal(second.jobs.length,0);await assert.rejects(completeGoogleJob(env,{source,lease:'wrong',data:{places:[{name:'Pizza'}]}}),{status:409});await completeGoogleJob(env,{...first.jobs[0],data:{places:[{name:'Pizza',lat:24,lng:121}],total:1,complete:true}});assert.equal((await readSaved(env,source)).places[0].name,'Pizza');await assert.rejects(completeGoogleJob(env,{...first.jobs[0],data:{places:[{name:'Late'}]}}),{status:409});db.close();});
test('background result failure preserves old snapshot and refuses partial data',async()=>{const {claimGoogleJobs,completeGoogleJob}=await import('../worker/saved-places.mjs');const {env,db}=setup(),p=provider();await enqueueSources(env,[source]);await processPlaces(env,p.fetcher);await enqueueSources(env,[source],{refresh:true});const {jobs}=await claimGoogleJobs(env);await assert.rejects(completeGoogleJob(env,{...jobs[0],data:{places:[{name:'Partial'}],complete:false,total:5}}),{status:400});await completeGoogleJob(env,jobs[0]);assert.equal((await readSaved(env,source)).places[0].name,'Pizza');assert.equal((await readSaved(env,source)).state,'failed');db.close();});

test('background credential only authorizes existing parsing jobs and validates returned leases',async()=>{const {api}=await import('../worker/api.mjs');const {env,db}=setup();env.MAP_PLACES_SYNC_KEY='a'.repeat(64);await enqueueSources(env,[source]);const base='https://site.test',request=(path,key,body)=>new Request(base+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+key,...(body?{Origin:base,'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const fetcher=()=>{throw Error('Public job API must not call GitHub or Google')};assert.equal((await api(request('/api/background/map-places/jobs','b'.repeat(64)),env,fetcher)).status,403);const r=await api(request('/api/background/map-places/jobs',env.MAP_PLACES_SYNC_KEY),env,fetcher);assert.equal(r.status,200);const {jobs}=await r.json();assert.equal(jobs.length,1);assert.equal((await api(request('/api/background/map-places/result',env.MAP_PLACES_SYNC_KEY,{...jobs[0],data:{places:[{name:'Coffee',lat:24,lng:121}],complete:true,total:1}}),env,fetcher)).status,200);assert.equal((await readSaved(env,source)).places[0].name,'Coffee');assert.equal((await api(request('/api/background/map-places/other',env.MAP_PLACES_SYNC_KEY),env,fetcher)).status,404);db.close();});
