export function accountPage(nonce){return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>我的創作者頁｜口袋地圖</title><style nonce="${nonce}">
[hidden]{display:none!important}*{box-sizing:border-box}body{font:16px system-ui;margin:0;color:#142641;background:#f7f9fc}main{max-width:1050px;margin:40px auto;padding:24px}a{color:#1647dd}h1{font-family:serif;line-height:1.5}.help{line-height:1.8;color:#65738a}button{padding:12px 18px;border:1px solid #dbe3ef;background:#edf3ff;color:#1647dd;border-radius:9px;font:inherit;cursor:pointer}button:disabled{opacity:.5;cursor:default}input,textarea{width:100%;padding:12px;border:1px solid #dbe3ef;border-radius:8px;font:inherit;background:white;color:#142641}label{display:block;margin:18px 0 8px}section{margin:28px 0}#login{max-width:480px}.layout{display:grid;grid-template-columns:340px 1fr;gap:36px}article{border:1px solid #dbe3ef;border-radius:20px;background:white;overflow:hidden;align-self:start}.banner{height:190px;background:linear-gradient(120deg,#dce8f9,#aec7e8);background-size:cover;background-position:center}.preview-body{padding:24px}.avatar{width:82px;height:82px;object-fit:cover;border-radius:50%;margin-top:-62px;border:4px solid white;background:#edf3ff;display:grid;place-items:center;color:#1647dd;font-size:30px}.preview-body p{white-space:pre-wrap;overflow-wrap:anywhere}.row{display:flex;gap:12px;flex-wrap:wrap;align-items:center}#status{padding:14px 0;line-height:1.7}#status[data-error=true]{color:#a12727}:focus-visible{outline:3px solid #e8aa45;outline-offset:3px}@media(max-width:750px){.layout{grid-template-columns:1fr}main{margin:10px auto}.preview{order:-1}}
</style></head><body><main><a href="https://r3dra1n.github.io/GoogleMapList/">← 回口袋地圖</a><h1>你的口袋世界</h1><p id="status" role="status">正在確認登入狀態…</p><section id="verify" hidden><p>確認後登入。請確認這是你剛才要求的驗證信。</p><button id="confirm">確認登入／綁定</button></section><section id="login" hidden><p class="help">目前採邀請制。使用 Google 或 Email 登入，同一帳號可在登入後綁定另一種方式。</p><button id="google" disabled>使用 Google 登入</button><form id="email-form"><label for="email">Email</label><input id="email" type="email" required autocomplete="email" maxlength="254"><button id="send-email" disabled>寄送登入連結</button></form><p class="help">驗證信 10 分鐘內有效，請在同一瀏覽器開啟並確認。</p></section><section id="editor" hidden><div class="row"><h2>個人頁設定</h2><button id="logout">登出</button></div><p class="help">修改會儲存至你的帳號；目前是個人頁草稿，尚不會公開在首頁或搜尋中。</p><div class="layout"><form id="profile-form"><label for="name">顯示姓名</label><input id="name" required maxlength="60"><label for="description">個人簡介</label><textarea id="description" rows="4" maxlength="500"></textarea><label for="links">社群連結（最多五行，每行：名稱 | HTTPS 網址）</label><textarea id="links" rows="3"></textarea><label for="avatar">頭像</label><input id="avatar" type="file" accept="image/jpeg,image/png,image/webp"><label for="banner">Banner</label><input id="banner" type="file" accept="image/jpeg,image/png,image/webp"><p class="help">圖片先在瀏覽器縮小；頭像最多 256 KB、Banner 最多 1 MB。照片請使用有權分享的素材。</p><button id="save">儲存個人頁</button></form><article class="preview"><div id="preview-banner" class="banner"></div><div class="preview-body"><span id="initial" class="avatar">W</span><img id="preview-avatar" class="avatar" hidden alt="頭像預覽"><h2 id="preview-name"></h2><p id="preview-description"></p></div></article></div><section><h2>登入方式</h2><p id="identities" class="help"></p><button id="link-google" disabled>綁定 Google</button><form id="link-email-form"><label for="link-email">綁定 Email</label><input id="link-email" type="email" required maxlength="254"><button id="link-email-button" disabled>寄送綁定驗證信</button></form></section></section></main><script nonce="${nonce}">
const $=id=>document.getElementById(id);let csrf='',version=0,config={},pending={},objectURLs=[];const token=new URLSearchParams(location.hash.slice(1)).get('token');if(token)history.replaceState(null,'','/account/verify');
function setStatus(message,error=false){$('status').textContent=message;$('status').dataset.error=error;}
async function api(path,options={}){const response=await fetch('/account/api/'+path,{...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...options.headers}});let data;try{data=await response.json()}catch{throw Error('服務暫時無法使用')};if(!response.ok)throw Error(data.error||'操作失敗');return data;}
function preview(){$('preview-name').textContent=$('name').value;$('preview-description').textContent=$('description').value;$('initial').textContent=$('name').value.slice(0,1)||'·';}
async function load(){config=await api('config');for(const id of ['google','link-google'])$(id).disabled=!config.google;for(const id of ['send-email','link-email-button'])$(id).disabled=!config.email;if(!config.enabled){setStatus('創作者登入尚未開放。');return;}if(token){$('verify').hidden=false;setStatus('請確認登入驗證');return;}await me();}
async function me(){try{const data=await api('me');csrf=data.csrf;version=data.profile.version;$('name').value=data.profile.name;$('description').value=data.profile.description;$('links').value=data.profile.links.map(x=>x.label+' | '+x.url).join('\\n');$('identities').textContent=data.identities.map(x=>x.provider+' · '+x.email).join(' ／ ');$('login').hidden=true;$('editor').hidden=false;preview();setStatus('已登入；你只能編輯自己的個人頁。');for(const slot of ['avatar','banner']){const r=await fetch('/account/api/media/'+slot);if(r.ok){const url=URL.createObjectURL(await r.blob());objectURLs.push(url);showImage(slot,url);}}}catch(e){$('login').hidden=false;setStatus('請登入；尚未設定的登入方式會保持停用。');}}
function showImage(slot,url){if(slot==='avatar'){$('preview-avatar').src=url;$('preview-avatar').hidden=false;$('initial').hidden=true;}else $('preview-banner').style.backgroundImage='url("'+url+'")';}
async function google(link){try{const data=await api('google/start',{method:'POST',body:JSON.stringify({link})});location.assign(data.url)}catch(e){setStatus(e.message,true)}}$('google').onclick=()=>google(false);$('link-google').onclick=()=>google(true);
for(const [form,id,link]of [['email-form','email',false],['link-email-form','link-email',true]])$(form).onsubmit=async e=>{e.preventDefault();const button=$(form).querySelector('button');button.disabled=true;try{const data=await api('email/start',{method:'POST',body:JSON.stringify({email:$(id).value,link})});setStatus(data.message)}catch(e){setStatus(e.message,true)}finally{button.disabled=!config.email}};
$('confirm').onclick=async()=>{$('confirm').disabled=true;try{await api('email/finish',{method:'POST',body:JSON.stringify({token})});location.replace('/account/')}catch(e){setStatus(e.message,true)}};
$('logout').onclick=async()=>{try{await api('logout',{method:'POST'});location.replace('/account/')}catch(e){setStatus(e.message,true)}};
$('name').oninput=preview;$('description').oninput=preview;
for(const slot of ['avatar','banner'])$(slot).onchange=async()=>{try{const file=$(slot).files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('請選擇 10 MB 以內的 JPG、PNG 或 WebP');const image=await createImageBitmap(file);if(image.width*image.height>40000000){image.close();throw Error('圖片解析度過大');}const max=slot==='avatar'?400:1400,scale=Math.min(1,max/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);image.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.82));if(!blob||blob.size>(slot==='avatar'?256*1024:1024*1024))throw Error('壓縮後仍太大，請選較小圖片');pending[slot]=blob;const url=URL.createObjectURL(blob);objectURLs.push(url);showImage(slot,url);setStatus('圖片已預覽，按儲存後才上傳。')}catch(e){setStatus(e.message,true)}};
$('profile-form').onsubmit=async e=>{e.preventDefault();$('save').disabled=true;try{const links=$('links').value.split('\\n').filter(x=>x.trim()).map(line=>{const i=line.indexOf('|');if(i<0)throw Error('每行連結請使用 名稱 | 網址');return {label:line.slice(0,i).trim(),url:line.slice(i+1).trim()}});const result=await api('profile',{method:'PATCH',body:JSON.stringify({name:$('name').value,description:$('description').value,links,version})});version=result.version;for(const [slot,blob]of Object.entries(pending)){try{await api('media/'+slot,{method:'POST',headers:{'Content-Type':blob.type},body:blob});delete pending[slot]}catch(e){throw Error('文字已儲存；圖片尚未完成：'+e.message)}}setStatus('個人頁草稿已儲存。')}catch(e){setStatus(e.message,true)}finally{$('save').disabled=false}};
window.addEventListener('pagehide',()=>objectURLs.forEach(URL.revokeObjectURL));load().catch(e=>setStatus(e.message,true));
</script></body></html>`;}
