import {accountEnhancements} from './account-design.mjs';
// Runs as a browser module. Firebase credentials stay in memory; the site uses an HttpOnly session cookie.
export function firebaseBrowserScript(common){return String.raw`
const $=id=>document.getElementById(id);let csrf='',version=0,config={},pending={},objectURLs=[],auth,sdk;
function setStatus(message,error=false){$('status').textContent=message;$('status').dataset.error=error;if($('auth-feedback')){$('auth-feedback').textContent=message;$('auth-feedback').dataset.error=error;}localize();}
async function api(path,options={}){const response=await fetch('/account/api/'+path,{...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...options.headers}});const data=await response.json();if(!response.ok){const e=Error(data.error||'操作失敗');e.status=response.status;throw e}return data;}
function preview(){$('preview-name').textContent=$('name').value;$('preview-description').textContent=$('description').value;$('initial').textContent=$('name').value.slice(0,1)||'·';}
function errorText(e){return ({'auth/invalid-credential':'Email 或密碼不正確，或請使用原本的登入方式。','auth/email-already-in-use':'這個 Email 已有帳號，請登入或重設密碼。','auth/weak-password':'密碼強度不足，請至少使用 8 個字元。','auth/invalid-email':'請輸入有效 Email。','auth/too-many-requests':'操作太頻繁，請稍後再試。','auth/popup-closed-by-user':'登入視窗已關閉。','auth/popup-blocked':'瀏覽器阻擋登入視窗，請允許彈出視窗後再試。','auth/account-exists-with-different-credential':'請先使用原本的方式登入此 Email。','auth/unauthorized-domain':'此網站網址尚未在 Firebase 授權。','auth/network-request-failed':'無法連線至登入服務，請檢查網路。'})[e.code]||e.message||'操作失敗';}
async function me(){try{const data=await api('me');csrf=data.csrf;version=data.profile.version;$('name').value=data.profile.name;$('description').value=data.profile.description;loadLinks(data.profile.links);$('identities').textContent=data.identities.map(x=>x.email).join(' ／ ');$('login').hidden=true;$('editor').hidden=false;$('profile-menu').hidden=false;$('menu-initial').textContent=data.profile.name.slice(0,1);preview();setStatus('已登入，修改後按儲存即可公開更新。');for(const slot of ['avatar','banner']){const r=await fetch('/account/api/media/'+slot);if(r.ok){const url=URL.createObjectURL(await r.blob());objectURLs.push(url);showImage(slot,url);if(slot==='avatar'){$('menu-photo').src=url;$('menu-photo').hidden=false;$('menu-initial').hidden=true;}}}}catch(e){if(e.status!==401)throw e;$('login').hidden=false;$('editor').hidden=true;setStatus('歡迎回來，或建立你的創作者帳號。');$('auth-feedback').textContent='';}}
async function complete(user){await sdk.reload(user);if(!user.emailVerified){$('verify').hidden=false;setStatus('請先在信箱點擊驗證連結，再按「我已驗證，繼續」。');return;}await api('firebase/session',{method:'POST',body:JSON.stringify({idToken:await user.getIdToken(true)})});$('password').value='';await sdk.signOut(auth);$('verify').hidden=true;location.replace('/');}
let authBusy=false;
async function attempt(work){if(authBusy)return;authBusy=true;const controls=[...$('login').querySelectorAll('button,input')];const disabled=controls.map(el=>el.disabled);controls.forEach(el=>el.disabled=true);$('login').setAttribute('aria-busy','true');try{await work()}catch(e){setStatus(errorText(e),true)}finally{controls.forEach((el,i)=>el.disabled=disabled[i]);$('login').removeAttribute('aria-busy');authBusy=false;}}
$('google').onclick=()=>attempt(async()=>{const result=await sdk.signInWithPopup(auth,new sdk.GoogleAuthProvider());await complete(result.user);});
$('email-form').onsubmit=e=>{e.preventDefault();attempt(async()=>{setStatus('正在登入…');const result=await sdk.signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);await complete(result.user);});};
$('register').onclick=()=>{if(!$('email-form').reportValidity())return;return attempt(async()=>{setStatus('正在建立帳號，接著會寄送驗證信…');const result=await sdk.createUserWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);$('password').value='';$('verify').hidden=false;setStatus('帳號已建立，正在寄送驗證信…');try{await sdk.sendEmailVerification(result.user)}catch(e){setStatus('帳號已建立，但驗證信寄送失敗。請按「重寄驗證信」，不需要重新註冊。',true);return;}setStatus('驗證信已寄出，請查看信箱與垃圾郵件。完成驗證後回到這裡繼續。');});};
$('reset-password').onclick=()=>{if(!$('email').reportValidity())return;return attempt(async()=>{await sdk.sendPasswordResetEmail(auth,$('email').value.trim());setStatus('若此地址可重設密碼，將收到重設信，請查看信箱與垃圾郵件。');});};
$('resend-verification').onclick=()=>attempt(async()=>{if(!auth.currentUser)throw Error('請先重新登入');setStatus('正在寄送驗證信…');await sdk.sendEmailVerification(auth.currentUser);setStatus('已重新寄出驗證信。');});
$('check-verification').onclick=()=>attempt(async()=>{if(!auth.currentUser)throw Error('請先重新登入');await complete(auth.currentUser);});
$('logout').onclick=()=>attempt(async()=>{await api('logout',{method:'POST'});if(auth)await sdk.signOut(auth);location.replace('/account/');});
`+common+accountEnhancements+String.raw`
async function load(){if(/Line\//i.test(navigator.userAgent)){$('embedded-note').hidden=false;}config=await api('config');if(!config.enabled||!config.firebase){setStatus('創作者登入尚未開放。');return;}$('access-note').textContent=config.invitationOnly?'試用期間，只有受邀且完成 Email 驗證的帳號能使用創作者後台。':'登入後，開始整理自己的口袋世界。';const app=await import('https://www.gstatic.com/firebasejs/12.4.0/firebase-app.js');sdk=await import('https://www.gstatic.com/firebasejs/12.4.0/firebase-auth.js');auth=sdk.getAuth(app.initializeApp(config.firebase));auth.languageCode=language;await sdk.setPersistence(auth,sdk.inMemoryPersistence);for(const id of ['google','email-login','register','reset-password'])$(id).disabled=false;await me();}
window.addEventListener('pagehide',()=>objectURLs.forEach(url=>URL.revokeObjectURL(url)));load().catch(e=>setStatus(errorText(e),true));
`;}
