import {readGoogleList,validListURL} from './google-list.mjs';
import {mapData} from './list-places.mjs';
import {myMapId} from '../public/model.js';
import {mapEntries} from '../public/catalog-model.js';
import photos from './place-photo-data.mjs';
import {ApiError} from './community.mjs';
const now=()=>Math.floor(Date.now()/1000);
export function sourceURL(value){if(typeof value!=='string'||value.length>4096||!validListURL(value))return null;const u=new URL(value);u.hash='';const mid=myMapId(u.href);return mid?'https://www.google.com/maps/d/viewer?mid='+encodeURIComponent(mid):u.href;}
export function attachPhotos(points){return points.map(p=>{const name=p.name.normalize('NFD').replace(/\p{M}/gu,'').toLowerCase(),key=name.includes('kalalau')?'Kalalau Beach':name.includes('crawler')?"Crawler's Ledge":name.includes('hanakap')?'Hanakapiai Beach':name.includes("ke'e")?'Kee Beach Kauai':'';const choices=photos[key]||[],photo=key==='Kalalau Beach'?choices.find(x=>x.title.includes('Sunset on Kalalau')):key==='Kee Beach Kauai'?choices.find(x=>x.title.includes("Ke'e Beach")):choices[0];return {...p,...(photo?{photo}:{})};});}
const xmlText=value=>String(value||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&(?:lt|gt|amp|quot|apos);|&#(?:x[\da-f]+|\d+);/gi,v=>{const named={'&lt;':'<','&gt;':'>','&amp;':'&','&quot;':'"','&apos;':"'"};if(named[v])return named[v];const n=parseInt(v.slice(2,-1).replace(/^x/i,''),/^&#x/i.test(v)?16:10);return n>0&&n<=0x10ffff?String.fromCodePoint(n):'';});
const tag=(xml,key)=>xmlText(xml.match(new RegExp('<'+key+'(?:\\s[^>]*)?>([\\s\\S]*?)</'+key+'>','i'))?.[1]);
export function parseMyMaps(xml){if(xml.length>2000000||!/<kml[\s>]/i.test(xml))throw Error('Invalid KML');const places=[],seen=new Set();for(const match of xml.matchAll(/<Placemark(?:\s[^>]*)?>([\s\S]*?)<\/Placemark>/gi)){const node=match[1],point=node.match(/<Point(?:\s[^>]*)?>([\s\S]*?)<\/Point>/i)?.[1];if(!point)continue;const [lng,lat]=tag(point,'coordinates').trim().split(',').map(Number),name=tag(node,'name').trim();if(!name||!Number.isFinite(lat)||!Number.isFinite(lng)||Math.abs(lat)>90||Math.abs(lng)>180)continue;const key=name.toLowerCase();if(seen.has(key))continue;seen.add(key);const fields={};for(const data of node.matchAll(/<Data\s+name=["']([^"']+)["'][^>]*>([\s\S]*?)<\/Data>/gi))fields[xmlText(data[1])]=tag(data[2],'value');places.push({name,lat,lng,note:fields['特色推薦與影片亮點']||'',address:fields['地址']||'',url:'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(lat+','+lng)});}return {places:attachPhotos(places),complete:true,total:places.length};}
export async function readSource(source,fetcher=fetch){const mid=myMapId(source);if(mid){const result=await mapData(new URL('https://site/api/map-data?mid='+encodeURIComponent(mid)),fetcher);return {...parseMyMaps(result.xml),sourceURL:source,provider:'mymaps'};}const result=await readGoogleList(source,fetcher);return {...result,places:attachPhotos(result.places),provider:'google'};}
export async function enqueueSources(env,values,{refresh=false}={}){let count=0;for(const source of new Set(values.map(sourceURL).filter(Boolean))){const time=now();await env.DB.prepare(`INSERT INTO saved_map_places(source_url,queued_at) VALUES(?,?) ON CONFLICT(source_url) DO UPDATE SET state=CASE WHEN ?=1 AND saved_map_places.state!='processing' THEN 'pending' ELSE saved_map_places.state END,attempts=CASE WHEN ?=1 AND saved_map_places.state!='processing' THEN 0 ELSE saved_map_places.attempts END,retry_at=CASE WHEN ?=1 AND saved_map_places.state!='processing' THEN 0 ELSE saved_map_places.retry_at END,queued_at=CASE WHEN ?=1 AND saved_map_places.state!='processing' THEN excluded.queued_at ELSE saved_map_places.queued_at END`).bind(source,time,Number(refresh),Number(refresh),Number(refresh),Number(refresh)).run();count++;}return count;}
export async function readSaved(env,value){const source=sourceURL(value);if(!source)throw new ApiError('此地圖不支援自動解析。',400);const row=await env.DB.prepare('SELECT state,payload,fetched_at,error FROM saved_map_places WHERE source_url=?').bind(source).first();if(!row)return {state:'pending',places:[],saved:false};const data=row.payload?JSON.parse(row.payload):{};return {...data,state:row.state,saved:Boolean(row.payload),fetchedAt:row.fetched_at,error:row.state==='processing'?'':row.error};}
export async function processPlaces(env,fetcher=fetch,limit=2,{myMapsOnly=false}={}){const time=now();const {results}=await env.DB.prepare("SELECT source_url FROM saved_map_places WHERE (?=0 OR source_url LIKE 'https://www.google.com/maps/d/viewer?mid=%') AND ((state IN ('pending','failed') AND attempts<3 AND retry_at<=?) OR (state='processing' AND lease_until<?)) ORDER BY queued_at LIMIT ?").bind(Number(myMapsOnly),time,time,limit).all();for(const row of results){const lease=crypto.randomUUID();const changed=await env.DB.prepare("UPDATE saved_map_places SET state='processing',lease_until=?,error=?,attempts=attempts+1 WHERE source_url=? AND ((state IN ('pending','failed') AND retry_at<=?) OR (state='processing' AND lease_until<?)) RETURNING attempts").bind(time+180,lease,row.source_url,time,time).first();if(!changed)continue;try{const data=await readSource(row.source_url,fetcher);if(!data.places.length&&data.total!==0)throw Error('No places');if(data.complete===false)throw Error('Partial list');await env.DB.prepare("UPDATE saved_map_places SET payload=?,fetched_at=?,state='ready',lease_until=0,error='' WHERE source_url=? AND error=?").bind(JSON.stringify(data),now(),row.source_url,lease).run();}catch(error){console.error('MAP_PLACES_SOURCE_FAILED',error.message);await env.DB.prepare("UPDATE saved_map_places SET state='failed',lease_until=0,retry_at=?,error=? WHERE source_url=? AND error=?").bind(now()+3600*Math.min(24,changed.attempts),'暫時無法解析來源；已保留先前成功儲存的景點。',row.source_url,lease).run();}}}
export async function discoverPlaces(env,fetcher=fetch){const response=await fetcher('https://r3dra1n.github.io/GoogleMapList/data.json',{signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error('Catalog unavailable');const catalog=await response.json();const urls=['cities','countries','themes'].flatMap(kind=>(catalog[kind]||[]).flatMap(item=>mapEntries(item,kind).map(e=>e.url)));const {results}=await env.DB.prepare('SELECT draft,published FROM pilot_lists').all();for(const row of results)for(const value of [row.draft,row.published])if(value){try{urls.push(JSON.parse(value).url)}catch{}}await enqueueSources(env,urls);}

// Google sources are parsed by the repository's background job. My Maps can be read by Workers.
export async function claimGoogleJobs(env,limit=6){const time=now();const {results}=await env.DB.prepare("SELECT source_url FROM saved_map_places WHERE source_url NOT LIKE 'https://www.google.com/maps/d/viewer?mid=%' AND ((state IN ('pending','failed') AND attempts<3 AND retry_at<=?) OR (state='processing' AND lease_until<?)) ORDER BY queued_at LIMIT ?").bind(time,time,limit).all();const jobs=[];for(const row of results){const lease=crypto.randomUUID();const claimed=await env.DB.prepare("UPDATE saved_map_places SET state='processing',lease_until=?,error=?,attempts=attempts+1 WHERE source_url=? AND ((state IN ('pending','failed') AND retry_at<=?) OR (state='processing' AND lease_until<?)) RETURNING attempts").bind(time+600,lease,row.source_url,time,time).first();if(claimed)jobs.push({source:row.source_url,lease});}return {jobs};}
export async function completeGoogleJob(env,input){if(!input||typeof input.source!=='string'||typeof input.lease!=='string')throw new ApiError('Invalid result',400);const source=sourceURL(input.source);const row=source&&await env.DB.prepare("SELECT attempts FROM saved_map_places WHERE source_url=? AND state='processing' AND error=?").bind(source,input.lease).first();if(!row)throw new ApiError('Job no longer active',409);let payload=null;
 if(input.data){const d=input.data;if(!Array.isArray(d.places)||d.places.length>5000||d.complete===false||(!d.places.length&&d.total!==0)||d.places.some(p=>typeof p.name!=='string'||!p.name.trim()||p.name.length>500||typeof(p.note||'')!=='string'||(p.note||'').length>20000||p.lat!=null&&(!Number.isFinite(p.lat)||Math.abs(p.lat)>90)||p.lng!=null&&(!Number.isFinite(p.lng)||Math.abs(p.lng)>180)))throw new ApiError('Invalid parsed places',400);const places=d.places.map(p=>({name:p.name,note:p.note||'',...(Number.isFinite(p.lat)&&Number.isFinite(p.lng)?{lat:p.lat,lng:p.lng,url:'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.lat+','+p.lng)}:{})}));payload=JSON.stringify({sourceURL:source,provider:'google',places:attachPhotos(places),total:Number.isSafeInteger(d.total)?d.total:places.length,complete:d.complete??null});if(payload.length>1000000)throw new ApiError('Result too large',413);}
 if(payload)await env.DB.prepare("UPDATE saved_map_places SET payload=?,fetched_at=?,state='ready',lease_until=0,error='' WHERE source_url=? AND error=?").bind(payload,now(),source,input.lease).run();else await env.DB.prepare("UPDATE saved_map_places SET state='failed',lease_until=0,retry_at=?,error=? WHERE source_url=? AND error=?").bind(now()+3600*Math.min(24,row.attempts),'暫時無法解析來源；已保留先前成功儲存的景點。',source,input.lease).run();return {ok:true};}
